scripts/pkg.in: Exit with exit code 1 instead of 0 on invalid mirror weight

diff --git a/scripts/pkg.in b/scripts/pkg.in
--- a/scripts/pkg.in
+++ b/scripts/pkg.in
@@ -109,8 +109,8 @@ get_mirror_url() {
 get_mirror_weight() {
 	source "$1"
 	if [[ ! "$WEIGHT" =~ ^[0-9]+$ ]]; then
-		echo "[!] invalid weight in mirror $1" > /dev/stderr
-		exit
+		echo "Error: Invalid weight in mirror $1" > /dev/stderr
+		exit 1
 	fi
 	echo $WEIGHT
 }
